PSA Presidental Election Results
%%%
<p>
On behalf of the Governing Board of the Philosophy of Science Association, it is my pleasure to announce that <a href="[PREFIX_FINAL]files/james-woodward.pdf" rel="download">Professor James Woodward</a>, J. O. and Juliette Koepfli Professor of Humanities and Professor of Philosophy at the California Institute of Technology, has been elected President of the Philosophy of Science Association. Professor Woodward will serve as PSA President from January 1, 2011, through December 31, 2012; until then he holds the office of PSA President-Elect. The Governing Board congratulates Professor Woodward and extends its deep appreciation to Professors Jeremy Butterfield and Margaret Morrison.
</p>
[split here]
<p>
As many PSA members know, James Woodward comes to the Presidency of the Philosophy of Science Association with a long history of service to the PSA and an impressive record of scholarship. He has been a member of both the Editorial Board for Philosophy of Science (1992-2000) and the Program Committee for the 1994 PSA Biennial Meeting. He chaired the PSA Nominating Committee in 1998-99, and was a member of the PSA Governing Board from 2000-2004. He wrote Making Things Happen: A Theory of Causal Explanation (Oxford, 2003), which won the Lakatos Prize, and is the author of many influential articles concerning causation and explanation, and, more recently, empirical investigations of causal learning, judgment, and cooperative and moral behavior. In his statement about the future of the Philosophy of Science Association (included in full in the attached biographical statement), Professor Woodward wrote that
</p>
<blockquote>
	<p>We should work to increase membership in the PSA, attendance at PSA meetings, and in general raise the profile of the PSA and make it a more vibrant and exciting organization. We should also work to strengthen academic links with other professional communities with which we share interests and also to increase the visibility of philosophy of science within philosophy. In the latter connection we might explore measures to encourage program committees at the various APA meetings to include more philosophy of science. We also might, as a group, make more of an effort to identify to our members new, intellectually exciting areas that philosophers of science may wish to explore.</p>
</blockquote>
<p>
The PSA Governing Board also congratulates and welcomes back Heather Douglas, Sandra Mitchell, John Norton, and P. Kyle Stanford, all for a second term on the PSA Governing Board. Since each accepted an automatic nomination to run a second time, and since the PSA By-Laws direct the Nominating Committee to determine new candidates only for vacant slots, these candidates ran unopposed.
</p>
<p>
Finally, I am happy to report that this first electronic PSA election was a success. At the election's beginning there were 737 Full Members of the PSA. 282, or 38%, of these voted electronically in response to email solicitations. I extend a special thanks to those many PSA members who voted. While we do not have turn-out rates from previous elections, it is worth noting that the absolute number of voters in this most recent election is a nearly 28% increase over the 221 members who voted in the previous election. Overall the 2008 PSA Election ran very smoothly, due in large part to the experience and dedication of Jay Malone and his staff at the History of Science Society. If you are a PSA Full Member and you encountered problems in voting electronically, however, or if you have any other comments, questions, or concerns about the 2008 PSA Election, please contact me at <a href="mailto:ghardcas@bloomu.edu" rel="email">ghardcas@bloomu.edu</a>.
</p>
